### PR TITLE
[WIP] Add pt-br translation

### PR DESCRIPTION
**Pull request by jessicapaz**

### CODE REVIEW

**Comment by aniav** [comment]
@jessicamorim42 this seems to be not translated. Is this a crowdin export of some kind?

**Comment by jessicamorim42** [comment]
I started translating the summary so I could translate the rest of the translation with other people

**Comment by aniav** [comment]
@jessicapaz I will close that for now, but you can totally reopen the pull request whenever you have made progress on that :)

**Comment by emmenezes** [comment]
@jessicapaz Hello, Jessica, do you still have an interest in translating to pt-br? I would like to help

**Pull request closed without merging**
