### PR TITLE
Tutorial on working with MongoDB

### PR DESCRIPTION
**Pull request by nesdis**

### CODE REVIEW

**Comment by nesdis** [comment]
Hello @aniav Can I expect this pull request to be merged?

**Comment by aniav** [comment]
Hey @nesdis I am not on top with DG repos recently. I will try to get to it on the weekend :)

**Comment by aniav** [comment]
Hey @nesdis so I am actually not sure we should merge these changes, as I think they don't belong in the tutorial.

The main issue I have here is that the Django Girls tutorial is created to teach Django and the basic ecosystem around it. The extensions are here for people who would like to go further with their learning, as additional steps to the main tutorial, but these are still basic ecosystem steps.

MongoDB support is not really a step further when learning Django when thinking of first steps with web development. Additionally this PR is not about installing MongoDB and just using it, it's about changing the whole structure of what we already created, without really telling people WHY they would need it.

I am happy to discuss the topic further. I might be missing a point here :)

**Comment by nesdis** [comment]
Hi @aniav I agree this PR is not meant for someone looking for basics of Django usage. I therefore put it in the 'extensions' page. 

> Additionally this PR is not about installing MongoDB and just using it, it's about changing the whole structure of what we already created, without really telling people WHY they would need it

This point is not clear to me. With the MongoDB you don't really need to change anything. If you are referring to MongoDB being a non-relational DB and 'changing the whole structure of Django for a non-relational DB' you maybe missing something. The latest version of Django lets you do relational stuff just like other relational DBs.

I am not a promoter for MongoDB but **I am a big fan** of Django. The reason I wrote this tutorial was for anyone who (for some reason must) uses MongoDB in the backend but doesn't want to stop using Django. It would be really unfortunate if they stopped using Django because they don't have information on how to use them together.

**Comment by nesdis** [comment]
Hey @aniav I have removed some parts of the tutorial which would probably not be as relevant to the audience. Does this make more sense to you?

**Comment by aniav** [comment]
> The reason I wrote this tutorial was for anyone who (for some reason must) uses MongoDB in the backend but doesn't want to stop using Django. It would be really unfortunate if they stopped using Django because they don't have information on how to use them together.

Well this pretty much sums up why these changes don't belong here. This is not a Django tutorial for anyone using MongoDB and wanting tu use Django. This is a tutorial for beginners. We assume their whole knowledge about programming and databases is what they find here. We don't target and don't want to target people already working with programming. There is no reason why MongoDB would belong here.

I would also like to talk more about the impact of such changes placed in a tutorial for beginners. Imagine you are just starting and all you know about websites is they live on the servers, they have a database (but you don't really know much about those), they have the visible part with HTML&CSS and they connect with Django which will do the magic to you. Now you barely know the Django ORM and that it's using SQL statements and calling it to retrieve data. You have just learned how all of this is coupled together and we throw you at MongoDB and tell you there is something like NoSQL and that it's a nested data structure, which you don't really understand. And you don't really get why you have learned everything about SQL when you can use NoSQL and which one should you use.
There is a lot of context going along introduction of something like that which we don't want to introduce in this tutorial.

**Comment by nesdis** [comment]
Hey @aniav Thank you for clarifying that. I assumed the django-girls tutorial was the 'introduction' to Django and 'extension' is 'what comes next' after the introduction. There is in fact a tutorial on launching the app on Heroku on the extension tutorial. (Which incidentally also provides MongoDB as the backend).

**Pull request closed without merging**
