### PR TITLE
put "raw" text outside of quotes & switch out <span> icons to include from static file

### PR DESCRIPTION
**Pull request by moonshain**
I was doing the tutorial during a Django Girls event. I copied the code from this tutorial and it didn't work, and my coach pointed out that the "raw" text didn't belong in the code and it was probably a mistake in the tutorial. 

I also changed two <span> icons which were broken to include from static icons like in main tutorial.

### CODE REVIEW

**Comment by das-g** [comment]
Hi @moonshain

Thank you for your contribution! This approach seems to fix the problem pointed out in #156. :tada:

**Comment by das-g** [comment]
I've now created #170 to fix the `{% raw %}`/`{% endraw %}` problem for all occurrences.

**Comment by crismotinha** [comment]
I'm just adding this comment to mention how proud I am of @moonshain , joining her first DG event today and besides finishing the tutorial and the extension, opening a PR to fix it <3

**Review by das-g — APPROVED** [review]
I've already merged the `{% raw %}` fix 9291130c525c4e24a2c45b4dcbd51a773ee9e8b4 as part of #170.

The change in d980264e74e95a472db84a4480a07c330dc76f50 about switching from glyphicons to Bootstrap icons to be consistent with the Django Girls tutorial looks good, too. :+1:

**Comment by das-g** [comment]
Congratulations, @moonshain

Your changes are now live on https://tutorial-extensions.djangogirls.org :tada:

**Pull request merged**
