### PR TITLE
Fix "Add publish button" and "Delete post" sections

### PR DESCRIPTION
**Pull request by kewtree1408**
Fixes issue: https://github.com/DjangoGirls/tutorial-extensions/issues/180

I'm not sure who should I add as a reviewer.
Do you know what should I do with other languages? I see that csrf token, for example, was added only to "en" version of the tutorial.

### CODE REVIEW

**Comment by das-g** [comment]
> I'm not sure who should I add as a reviewer.

You don't have to add any. Potential reviewers can also add themselves.

**Comment by das-g** [comment]
> Do you know what should I do with other languages?

I don't remember whether we have Crowdin for the extensions now. If not, could you apply your changes to the other languages, too? As these changes are all only in the code blocks, that should be possible without having to know those languages.

**Comment by kewtree1408** [comment]
Hey @das-g ,

Thanks for your comments!

I've changed the code for all of the translations.
I've also removed all `glyphicons` classes, because they aren't supported in Bootstrap 5, as was mentioned in this issue as well: https://github.com/DjangoGirls/tutorial-extensions/issues/145
and was partially changed and mentioned in this PR: https://github.com/DjangoGirls/tutorial-extensions/pull/179

Let me know if other changes needed!

**Review by das-g — APPROVED** [review]
Looks good to me.

**Pull request merged**
