### PR TITLE
[Japanese translation]Fix the link to each chapter

### PR DESCRIPTION
**Pull request by kaizumaki**
The link to each chapter in ja/README.md was incorrect, so it was fixed.

### CODE REVIEW

**Comment by kaizumaki** [comment]
Thank you for merging. However, gitbook has not been updated. Is there any problem?

**Comment by das-g** [comment]
> Thank you for merging.

You're welcome! Thank you for the fix!

> However, gitbook has not been updated.

It hasn't, indeed. Thanks for making us aware!

> Is there any problem?

I don't know, but as the update should not take over an hour, I'd say yes. I'll ask around.

**Comment by kaizumaki** [comment]
My changes have not yet been reflected in gitbook. Could gitbook build fail?

**Comment by das-g** [comment]
> My changes have not yet been reflected in gitbook. Could gitbook build fail?

I noticed that, too. Sorry for the inconvenience.

I don't know what's up or how to investigate it. @magul can you help?

**Comment by magul** [comment]
The details of these tutorial extensions on GitBook are here: https://legacy.gitbook.com/book/djangogirls/django-girls-tutorial-extensions/details

Unfortunately, I'm not able to refresh the content of the main branch there (probably need to be GitHub organization owner), so we should either merge another pull request (or somehow different change tip of `master`) or ask somebody with sufficient permissions to refresh that from GitBook side (can we ask you? @aniav @RachellCalhoun ).

**Comment by kaizumaki** [comment]
@magul @das-g 
Thank you for all your help.

The pull request #129 I issued was merged, so it seems that the gitbook rebuild was successful (Correcting link was working well).

**Pull request merged**
