### PR TITLE
Restructure project to work with multiple languages

### PR DESCRIPTION
**Pull request by Morozzzko**
The basic Django Girls tutorial has been translated into multiple languages and provides us with a great study material. However, Django Girls tutorial extensions are only available in English, which makes it difficult for girls to continue their learning. 

Moreover, current tutorial-extensions layout was designed to support only one language. Design changes must have been made in order to add more languages.

This pull request proposes the neccessary changes, moving necessary files into separate directory as well as adding language-picker plugin.

### CODE REVIEW

**Comment by aniav** [comment]
I know this has been hanging here for a long time. Do we want to introduce multiple languages for tutorial-extensions? i am not sure what is our overall idea on this book :)

**Comment by helenst** [comment]
@aniav I think it is a nice idea to have multiple languages, similar to the tutorial. :) It might be harder to get people translating since the extensions get less attention anyway. But it's nice if the option is there for them.

**Comment by goanpeca** [comment]
@aniav, @helenst what is the update on this front?

I am starting to work on Spanish translations for the extensions and having this work merged would make life easier.

---

I don't know if the plan is to keep using the crowdsource translation service as for the main tutorial. I am not a fan of that system, and although I understand the idea and "easy of use" style for non coders to help with translating, it just makes progress unbearably slow in general.

Thougths on this?

**Comment by aniav** [comment]
@Morozzzko @goanpeca I am happy to merge this if anyone can resolve the conflicts 👍

**Comment by Morozzzko** [comment]
See #89

**Pull request closed without merging**
